apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-hasher
  namespace: user-hasher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-hasher
  template:
    metadata:
      name: user-hasher-pod
      labels:
        app: user-hasher
    spec:
      containers:
        - name: user-hasher
          image: ashokdanaraddi/user-hasher:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              cpu: "400m"
              memory: "400Mi"
          env:
            - name: USER_SALT
              valueFrom:
                secretKeyRef:
                  key: name
                  name: user-salt-secret